### ISSUE TITLE
Where to subscribe the topic "/odom_lio" ?

### ISSUE THREAD

**Issue by zhouyong1234** [BruceXSK/fast_lio_localization#2]
I can't find where to subscribe the topic "/odom_lio", so I'm unable to run the program, can you tell me how to solve it ?

**Comment by BruceXSK** [comment]
> I can't find where to subscribe the topic "/odom_lio", so I'm unable to run the program, can you tell me how to solve it ?

My apologise, I forgot to mention that I remap the FAST-LIO original odometry topic `/Odometry` to `/odom_lio`. You can just change the topic `/odom_lio` in src/fast_lio_localization.cpp 80 line to `/Odometry` to adpot the FAST-LIO.
