### ISSUE TITLE
请问是否有发出全局定位信息？

### ISSUE THREAD

**Issue by InterKnight** [BruceXSK/fast_lio_localization#3]
你好，我观察项目里只发布了/map_cloud信息，并没有发布/localization信息，请问是吗？

**Comment by BruceXSK** [comment]
一共有两个节点，`map_loader`是加载PCD地图文件并发布`/map_cloud`点云信息的，`fast_lio_localization`节点是会发布定位信息的

**Comment by InterKnight** [comment]
> 一共有两个节点，`map_loader`是加载PCD地图文件并发布`/map_cloud`点云信息的，`fast_lio_localization`节点是会发布定位信息的

了解了，里面的tf就是定位信息。请问能输出全局坐标下的速度，角速度，加速度吗？我看目前只输出了位姿

**Comment by BruceXSK** [comment]
> 

似的这个只是用来做全局定位的，没有速度。
另外实际上FAST_LIO会存在静态误差，所以单纯靠FAST_LIO算出来的速度和加速度并不准，会有明显的抖动。如果需要计算速度，建议使用[robot_localization](http://wiki.ros.org/robot_localization)做里程计和IMU融合，然后再根据全局定位信息变换到全局坐标系下

**Comment by BruceXSK** [comment]
> > 一共有两个节点，`map_loader`是加载PCD地图文件并发布`/map_cloud`点云信息的，`fast_lio_localization`节点是会发布定位信息的
> 
> 了解了，里面的tf就是定位信息。请问能输出全局坐标下的速度，角速度，加速度吗？我看目前只输出了位姿

是的这个只是用来做全局定位的，没有速度。
另外实际上FAST_LIO会存在静态误差，所以单纯靠FAST_LIO算出来的速度和加速度并不准，会有明显的抖动。如果需要计算速度，建议使用[robot_localization](http://wiki.ros.org/robot_localization)做里程计和IMU融合，然后再根据全局定位信息变换到全局坐标系下

**Comment by InterKnight** [comment]
> > > 一共有两个节点，`map_loader`是加载PCD地图文件并发布`/map_cloud`点云信息的，`fast_lio_localization`节点是会发布定位信息的
> > 
> > 
> > 了解了，里面的tf就是定位信息。请问能输出全局坐标下的速度，角速度，加速度吗？我看目前只输出了位姿
> 
> 是的这个只是用来做全局定位的，没有速度。 另外实际上FAST_LIO会存在静态误差，所以单纯靠FAST_LIO算出来的速度和加速度并不准，会有明显的抖动。如果需要计算速度，建议使用[robot_localization](http://wiki.ros.org/robot_localization)做里程计和IMU融合，然后再根据全局定位信息变换到全局坐标系下

非常感谢
