### ISSUE TITLE
请教关于里程计的问题

### ISSUE THREAD

**Issue by InterKnight** [BruceXSK/fast_lio_localization#4]
您好，我接触SLAM不久，感谢开源此项目，有3个问题想请教一下：
1，我的理解是否有误：实现定位需要依赖里程计的信息，此项目中，里程计的信息是通过 fast_lio 项目输出的是吗？
2，fast_lio项目中，需要配置Lidar和IMU的外参（距离以及旋转角），但是在此项目中，我没有发现这部分配置，请问这部分配置在哪里？
3，假设我用一套设备建图，另一套设备定位，两套设备的外参不一样，那我在定位的时候（使用此项目），应该用建图时的外参，还是实际的定位设备的外参？
非常感谢！

**Comment by BruceXSK** [comment]
> 
您好
1. 您理解的没有错，这个项目中的里程计数据是使用的fast_lio输出的数据，所以实际上机器人底盘编码器输出的里程计消息是被抛弃掉了。最好的选择应该是lidar+imu+odom三者融合共同输出一个里程计信息，但是fast_lio只使用了前两者，我理解的是，毕竟fast_lio是一个VIO的工作，这样做可以适用于手持建图，但是对于具有编码器的机器人来说就丢失了一些传感器信息。因为我本身并不是做机器人定位的，所以没有能力做这一块的工作，如果您能找到ldar+imu+odom融合的项目也希望能分享给我，非常感谢
2. 这个项目没有对fast_lio进行修改，所以您要使用的话还是需要单独clone fast_lio的原项目，外参是配置在那个里面的。这个项目做点云匹配只用到了激光雷达的点和点云地图，因此并不需要imu的信息，imu只是用在fast_lio里面的
3. 要使用实际的定位设备的外参的

**Comment by InterKnight** [comment]
好的，非常感谢
