### ISSUE TITLE
关于雷达点云格式的问题

### ISSUE THREAD

**Issue by DAR-fly** [BruceXSK/fast_lio_localization#6]
您好，关于使用fast-lio进行定位，fast-lio源码中要求的是带有ring和time信息的雷达point，请问该项目输入的雷达点云格式是XYZI还是XYZIRT？如果需要的是XYZIRT，自己录制的bag中点云只包含XYZI，那又如何在源码中计算time信息？
非常感谢！

**Comment by BruceXSK** [comment]
您好，这个项目是独立于fast-lio外的，在这个项目里面只需要XYZI的点云跟点云地图做点云配准
